### ISSUE TITLE
Feature suggestion - Rename artboards with number sequence, from left to right based on their X and Y positions.

### ISSUE THREAD

**Issue by vwsvws** [rodi01/RenameIt#132]
Thank you for such useful plugin! I use it almost daily. Here's a quick suggestion:

It seems like currently RenameIt use the order of the layers to apply number sequences, but what if there is an option to use the X and Y positions of the artboards instead? 

I organize my artboards in rows, each row is a sequence, from left to right, top to bottom, to create a visual hierarchy. When I rearrange some artboards, even though my rows are now in the right order, the order of the layers are usually not, so when I use the plugin to rename the row with ascending number sequence, the numbers are not in the right order, unless I also reorder the layers. 

This seems like a common practice amongst all the designers I know. Is there a workaround?

**Comment by krisniles** [comment]
Same! Sequencing based on artboard Y positions would be amazing. Without this, I find myself using Enumerator, and not able to use RenameIt for most renaming.

**Comment by nOttenga** [comment]
Same here!
I love this plugin, but without this feature it's really complex to use - you can sort manually the artboards on the layers list but it's too long to do.

**Comment by rodi01** [comment]
Do you guys have any suggestions as to which direction the sequence should be prioritized? 
Ideally, it would support both directions but for now, if I were to rename columns and rows second would it make sense? 

Like this example
![Artboard](https://user-images.githubusercontent.com/52461/80042561-4122c980-84b4-11ea-9b9c-263b79367c83.png)

**Comment by nOttenga** [comment]
I usually structure my sketch file in rows so yes, this priority row by row, from left to right would work perfectly for me

**Comment by krisniles** [comment]
Renaming across the row (Y position) is my primary use-case. That's 90% of the battle. Renaming across both rows and columns (as shown in the image) would be awesome, but not as critical. Does that answer your question @rodi01?

**Comment by rodi01** [comment]
I'm working on it, I'm hoping to get it done by the weekend.

**Comment by rodi01** [comment]
If anyone wants to help me test this featured it would be appreciated. YOu can download the DEV version of the plugin here: https://github.com/rodi01/RenameIt/releases/download/4.5.0-DEV/Rename-It.sketchplugin.zip

I'm still working on the UI but it should be 100% functional.

<img width="504" alt="Screen Shot 2020-04-24 at 4 47 20 PM" src="https://user-images.githubusercontent.com/52461/80265159-71e93700-864b-11ea-9a59-0b99d5da604b.png">

Thank You!

**Comment by krisniles** [comment]
@rodi01 - Apologies for the delay! I gave it a run through, and it's working fantastically! I shifted artboards around, misaligned them a bit, renamed a whole x/y offset collection, but couldn't get it to break. 

The only thing that was slightly confusing was this: When selecting artboards that vary across both X and Y positions, and then choosing to rename based on X position, the preview _lists_ the artboards in a non-intuitive order (x position, then y position?). When the two above conditions aren't true, the preview reads `1,2,3,4 ...`, which feels right, because that's ultimately the end result (even though it wraps across columns, etc). Lemme know if I'm missing something there. 

![image](https://user-images.githubusercontent.com/11843095/80387309-bc460000-8865-11ea-8a63-9dc7e297db6c.png)

**Comment by krisniles** [comment]
Food for UI thought: Adding a dropdown that shows the rename pattern (stealing a page from the Craft plugin). With this approach, you could always show the preview as the sequential order the artboards will be renamed in, since the rename pattern is clear.

![Group 11](https://user-images.githubusercontent.com/11843095/80395887-17312480-8871-11ea-91b7-f2177d6aaa4c.png)

**Comment by rodi01** [comment]
@krisniles wow! thanks for testing the feature and for your detailed explanation.

In regards to the preview being out of order, I was planning to fix that in the final release. Good catch. 

I love your UI/UX suggestion for the order dropdown. For the initial release, I won't have time to do the last item since the same can be accomplished by using the keyword "%n" in lowercase. I do think that's a better move going forward, so I will change that in the future.

Thanks for all your suggestions. Hopefully, I'll get to finish the final release soon.
