### ISSUE TITLE
simpler menu options

### ISSUE THREAD

**Issue by Raghav789** [rodi01/RenameIt#74]
First of all, Thank you for this amazing plug-in
right now 'Rename selected layers' and 'Rename selected artboards' both almost do the same thing If I select artboards and chose 'Rename selected layers' it works! (if try to do the opposite it won't work) 
same can be said for the 'find and replace the layer' it will also work with selected artboards.

the way I see it there need to be only two option 1.Rename 2.Find and Replace and in the popup window, there should be an option to check/uncheck selected(which will be checked by default if the user has a selection)

and In the feature builds you can introduce further control whether it should apply to All or artboards, groups, layer in the popup.

**Comment by rodi01** [comment]
Thanks for the suggestion @Raghav789. 

The "Rename selected artboards" works in a different way. It will always select the artboard of the selection. If you have a layer selected, it will look for its artboard. 

This was a very popular feature request, before that I only had the "rename selected layers" menu that behaved the same way as it is today. That's why I didn't remove the ability to rename the artboards, I personally don't use the artboard feature.

I agree that the menu needs work. I will put more thought around it, I like your solution for the menu. I just have to figure out the the user case where the user wants to rename the parent artboard. 

Any ideas are welcome.

**Comment by Raghav789** [comment]
Thank you for considering it
I think the reason behind  "Rename selected artboards"  being very popular request was that, back then the only way to select an artboard was to zoom in and click on each individual artboard names while holding SHIFT. Zooming out clicking and dragging would only select the layer, not artboard. However, sketch fixed that issue now.
I wouldn't dismiss the usefulness of this feature so, I would recommend two options in the popup. 
Rename
1.Selection (either artboard, group or layer)
2.Parent artboard 
find and Replace
1.Selection(either artboard, group or layer)
2.Parent artboard 
3.Current page
How about it?
